version: "3.1"

services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Statement
    ports:
      - 27017:27017
